### ISSUE TITLE
Linux install results in permission denied 

### ISSUE THREAD

**Issue by alphafox02** [EFForg/rayhunter#73]
Running the latest release Linux installer results in this against a compatible hotspot I picked up today. Ran with and without sudo, but at a glance it appears its on the Orbic end. 

```
dragon@dragon:~/Downloads/release$ ./install-linux.sh 
Using adb at /usr/bin/adb
Force a switch into the debug mode to enable ADB
Device already in command mode. Doing nothing...
adb enabled, waiting for reboot... it's alive!
waiting for atfwd_daemon to startup... done!
./rootshell: 1 file pushed. 1.0 MB/s (936092 bytes in 0.937s)
uid=0(root) gid=0(root)
we have root!
./config.toml.example: 1 file pushed. 0.0 MB/s (316 bytes in 0.007s)
./rayhunter-daemon: 1 file pushed. 1.3 MB/s (11574720 bytes in 8.557s)
./scripts/rayhunter_daemon: 1 file pushed. 0.1 MB/s (580 bytes in 0.005s)
./scripts/misc-daemon: 1 file pushed. 0.4 MB/s (2302 bytes in 0.005s)
cp: can't create '/etc/init.d/rayhunter_daemon': Permission denied
cp: can't create '/etc/init.d/misc-daemon': File exists
chmod: /etc/init.d/rayhunter_daemon: No such file or directory
chmod: /etc/init.d/misc-daemon: Operation not permitted
waiting for reboot.../bin/bash: /sbin/reboot: Permission denied

```

**Comment by alphafox02** [comment]
Also tried manually within Orbic after using the rootshell to obtain root verified by whoami

```
hostid               rev                  xargs
hostname             rm                   xz
hush                 rmdir                xzcat
id                   rootshell            yes
install              rpm                  zcat
ionice               rpm2cpio
bash-4.3# cp /tmp/rayhunter_daemon /etc/init.d/rayhunter_daemon
cp: can't create '/etc/init.d/rayhunter_daemon': Permission denied
bash-4.3# whoami
root
bash-4.3# 
```

**Comment by alphafox02** [comment]
I'm noticing that the hotspot purchased from the repo link that I'm sitting on a v 1.3.0 firmware which seems far newer then what I can find mentioned online. I'm wonder if that's an issue?

**Comment by alphafox02** [comment]
My mistake, I just realized that running setup per the directions was downloading an old release which didn't have the commit in install-common that worked around the root issue. I have it installed and up and running now.

**Comment by cooperq** [comment]
Yes this is a known issue and we have a fix for it in main but it hasn't made its way into the release yet, sorry!

**Comment by alphafox02** [comment]
No problem, I actually have two pucks now since I briefly thought it was a firmware thing. Interestingly enough, the second one that arrived has a 1.2 version while the first one has a 1.3. 

Is there anyway I can setup a lab environment in an attempt to trigger one of the events? Say an SDR running srsRan or some other setup? I’d just like to understand how the puck is doing what it’s doing, like is it only connecting to one bts/cell and monitoring that or just checking different known providers (I think this is defined in a file). 

I’m only used to crocodile Hunter, but been slowly reading the code in this repo to understand a little more about what’s going on.
